import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import "@dips/puls-typography/dist/typography-next.css";
import "@dips/puls-core-react-components/index.css";
 
const circularFont = localFont({
    variable: "--font-circular",
    src: [
        { path: "../../node_modules/@dips/puls-typography/lib/font/circular/CircularXXWeb-Book.woff", weight: "400" },
        { path: "../../node_modules/@dips/puls-typography/lib/font/circular/CircularXXWeb-Medium.woff", weight: "500" },
        { path: "../../node_modules/@dips/puls-typography/lib/font/circular/CircularXXWeb-Bold.woff", weight: "700" }
    ]
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${circularFont.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
