-- Add migration script here

CREATE TABLE events(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title TEXT NOT NULL, description TEXT NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, location TEXT NOT NULL)
