-- Add migration script here

CREATE TABLE schedules(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_id bigint REFERENCES events(id), next_occurrence TIMESTAMPTZ NOT NULL, reoccuring_interval TEXT NOT NULL)
